//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class BranchOffices
    {
        public int IdOffice { get; set; }
        public int BranchZone { get; set; }
        public string BranchAddress { get; set; }
        public string Phone { get; set; }
        public System.TimeSpan OpTime { get; set; }
        public System.TimeSpan CloseTime { get; set; }
        public bool Active { get; set; }
        public System.Data.Entity.Spatial.DbGeography MarkerLocation { get; set; }
    }
}
