//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employees
    {
        public int ID { get; set; }
        public string EmpName { get; set; }
        public string EmpLastName { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string EmpUser { get; set; }
        public string EmpPassword { get; set; }
        public string Celphone { get; set; }
        public string EmpAddress { get; set; }
        public string EmpRole { get; set; }
        public string Licence { get; set; }
    
        public virtual Roles Roles { get; set; }
        public virtual Licenses Licenses { get; set; }
    }
}
