//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class HomePickups
    {
        public int IdHomePickup { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public string Note { get; set; }
        public string PickupAddress { get; set; }
        public int PickUpZone { get; set; }
        public System.Data.Entity.Spatial.DbGeography PickUpLocation { get; set; }
        public int ShippmentId { get; set; }
        public double Latitude { get; set; }
        public double Longitude { get; set; }

        public virtual Shippments Shippments { get; set; }
        public virtual Zones Zones { get; set; }
    }
}
