//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShippmentStages
    {
        public int IdShSt { get; set; }
        public int ShippmentID { get; set; }
        public int StageID { get; set; }
        public int EmployeeID { get; set; }
        public System.DateTime DateTimeStage { get; set; }
        public Nullable<int> RouteShapeID { get; set; }
        public Nullable<int> VehicleID { get; set; }
    
        public virtual Employees Employees { get; set; }
        public virtual Shippments Shippments { get; set; }
        public virtual ShRoute ShRoute { get; set; }
        public virtual Stages Stages { get; set; }
        public virtual Vehicles Vehicles { get; set; }
    }
}
