//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShRoute
    {
        public int IdRoute { get; set; }
        public decimal OrigLatitude { get; set; }
        public decimal OrigLongitude { get; set; }
        public int IdShSt { get; set; }
        public int IdShippment { get; set; }
        public int IdSStage { get; set; }
        public int EmpID { get; set; }
        public Nullable<int> Vehicle { get; set; }
    
        public virtual ShippmentStages ShippmentStages { get; set; }
    }
}
